resource_group_name = "inkwell-rg"
location            = "uksouth"
cluster_name        = "inkwell-aks"
acr_name            = "inkwellacr"
app_name            = "ink-well"
app_plan_name       = "inkwell-asp"
image_name          = "inkwell-img"
