on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action'
        required: true
        default: 'create'
        options:
          - create
          - destroy

env:
  RESOURCE_GROUP: inkwell_rg
  AKS_CLUSTER_NAME: inkwell-aks-cluster
  ACR_NAME: inkwellcontrepo
  IMAGE_NAME: inkwell-image

jobs:
  terraform-lifecycle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init -input=false

      - name: Terraform Format
        run: |
          cd infrastructure
          terraform fmt -check=true -recursive

      - name: Terraform Action
        run: |
          cd infrastructure
          if [ "${{ github.event.inputs.action }}" == "create" ]; then
            terraform apply -auto-approve
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action specified. Please choose 'create' or 'destroy'."
            exit 1
          fi
